server:
  port: 8080
spring:
  application:
    name: redis-001-jedis
  redis:
    lettuce:
      pool:
        max-wait: -1ms
        max-active: 8
        max-idle: 8
        min-idle: 0
      cluster:
        refresh:
          adaptive: true
          period: 2000
    password: 111
    cluster:
      nodes: 192.168.88.130:6381,192.168.88.130:6382,192.168.88.130:6383,192.168.88.130:6384,192.168.88.130:6385,192.168.88.130:6386
      max-redirects: 3